server:
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: user
      password: 1234
  datasource:
    username: ${DATABASE_USERNAME} # ????? ??? DATABASE_USERNAME=root;
    password: ${DATABASE_PASSWORD} # ????? ??? DATABASE_PASSWORD= *****;
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/JavaERP
jpa:
  hibernate:
    ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        generate_statistics: true

logging:
  level:
    org.hibernate.SQL: ERROR
    org.hibernate.type: ERROR
    org.hibernate.type.descriptor.sql: ERROR
    org.hibernate.stat: ERROR

jwt:
  secret-key-source: ${JWT_SECRET_KEY}